### ISSUE TITLE
엔티티 객체가 API의 반환값으로 사용되고 있습니다.

### ISSUE THREAD

**Issue by tlsgmltjd** [themoment-team/onboarding-server#18]
현재 모든 API에서 반환으로 엔티티 객체를 반환하고 있습니다.
이렇게 된다면 불필요한 정보를 넘겨준다던가 민감한 정보들을 노출하게 됩니다. (ex. 유저의 비밀번호)
response, request body에서 dto 객체를 활용하여 개선해보시기 바랍니다.

<img width="532" alt="스크린샷 2024-06-10 오전 9 19 23" src="https://github.com/themoment-team/onboarding-server/assets/131235625/3090c2eb-f76d-4d86-937e-4d8549a5d33a">

**Comment by kimjihoon3106** [comment]
UserDto 객체를 생성하였습니다 필요한 정보만 변환하여 반환함으로써 이러한 문제를 해결할 수 있었습니다.
b5c2f01682f05fffcabadcdf0e65d977ec3cd086
a371e8b3007d030bde96b9c25679039155423659
b2b5569518d6f80bf1b5506a06623da4bc3b5ebe
c7d0cb5ef1d45331e13a775576784418b40dfa0c

**Comment by tlsgmltjd** [comment]
네, 해당 부분 말고도 댓글이나 게시글 API도 엔티티를 반환하는 형식은 좋지 않습니다. 모두 dto를 사용하여 request, response 하도록 변경해보세요.
더모먼트 리포지토리를 참고하여 구현해봐도 좋을것 같아요.

**Comment by kimjihoon3106** [comment]
31d6d93f0a467ce9a79e02c3a85a9a9c5675cced 144184e3f839c5003a23c29f48bee8b4c4fd094b 310e8af0db96aa9098d82c4567a21e75b7c026d2 9e95d082cac7817641c6f0f9574c2df91962f960 b2ccaaa4ebada7c21f80316c4b8e52c9ba6f8f13 9a7e9ba4b446fd3a90b83d96b8f2865aa99b4608 8c174452048850d9a4550fa5059d1b5c4d73d83f 53884d96a1fdd481f704c051db887925e3844a5c

다른 API도 엔티티를 반환하는 형식에서 모두 Dto 객체를 반환하는 형식으로 변경하였습니다.
불필요한 정보 노출에대한 생각은 하지 못했는데 피드백 감사합니다!

**Comment by kimjihoon3106** [comment]
31d6d93f0a467ce9a79e02c3a85a9a9c5675cced 144184e3f839c5003a23c29f48bee8b4c4fd094b 310e8af0db96aa9098d82c4567a21e75b7c026d2 9e95d082cac7817641c6f0f9574c2df91962f960 b2ccaaa4ebada7c21f80316c4b8e52c9ba6f8f13 9a7e9ba4b446fd3a90b83d96b8f2865aa99b4608 8c174452048850d9a4550fa5059d1b5c4d73d83f 53884d96a1fdd481f704c051db887925e3844a5c

다른 API도 엔티티를 반환하는 형식에서 모두 Dto 객체를 반환하는 형식으로 변경하였습니다.

**Comment by tlsgmltjd** [comment]
네~ 수고하셨습니다 이슈 closed 하겠습니다.
